version: '3.9'
services:
    app:
      build:
        context: .
        dockerfile: Dockerfile
      ports:
        - "15400:15400"
      volumes:
        - "./app:/code/app"
        - "./requirements.txt:/code/requirements.txt"
      environment:
        - DATABASE_URL=postgresql://postgres_user:postgres_password@postgres:5432/postgres_db
        - APP_HOST=0.0.0.0
        - APP_PORT=15400
      command: ["uvicorn", "app.index:app", "--host", "${APP_HOST}", "--port", "${APP_PORT}"]

    postgres:
      image: postgres
      container_name: postgres
      ports:
        - '6500:5432'
      restart: always
      env_file:
        - ./.env
      volumes:
        - postgres-db:/var/lib/postgresql/data
      environment:
        - POSTGRES_USER=postgres_user
        - POSTGRES_PASSWORD=postgres_password
        - POSTGRES_DB=postgres_db

volumes:
  postgres-db:
